apiVersion: v1
kind: Service
metadata:
  name: evaluation
  namespace: togglemaster
  labels:
    app: evaluation
spec:
  type: ClusterIP
  selector:
    app: evaluation
  ports:
    - port: 5000
      targetPort: 5000
