apiVersion: v1
kind: Service
metadata:
  name: targeting
  namespace: togglemaster
  labels:
    app: targeting
spec:
  type: ClusterIP
  selector:
    app: targeting
  ports:
    - port: 5000
      targetPort: 5000
