apiVersion: v1
kind: Service
metadata:
  name: flag
  namespace: togglemaster
  labels:
    app: flag
spec:
  type: ClusterIP
  selector:
    app: flag
  ports:
    - port: 5000
      targetPort: 5000
