name: CI - evaluation

on:
  push:
    branches: [main]
    paths:
      - "services/evaluation/**"
      - ".github/workflows/ci-evaluation.yml"
      - ".github/workflows/_reusable-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "services/evaluation/**"
      - ".github/workflows/ci-evaluation.yml"
      - ".github/workflows/_reusable-ci.yml"
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/_reusable-ci.yml
    with:
      service: evaluation
